from __future__ import annotations
import os
from datetime import datetime, timezone
from typing import Any
from uuid import uuid4
from sqlalchemy import Boolean, DateTime, Float, ForeignKey, Index, Integer, JSON, String, Text, UniqueConstraint, create_engine, inspect, text
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column, sessionmaker

DATABASE_URL = os.getenv("DATABASE_URL", "postgresql+psycopg://razorrecover:razorrecover_dev@localhost:5432/razorrecover")
engine = create_engine(DATABASE_URL, connect_args={"check_same_thread": False} if DATABASE_URL.startswith("sqlite") else {}, pool_pre_ping=True)
SessionLocal = sessionmaker(bind=engine, expire_on_commit=False)
def uid() -> str: return str(uuid4())
def utcnow() -> datetime: return datetime.now(timezone.utc).replace(tzinfo=None)
class Base(DeclarativeBase): pass
class Times:
    created_at: Mapped[datetime] = mapped_column(DateTime, default=utcnow, index=True)
    updated_at: Mapped[datetime] = mapped_column(DateTime, default=utcnow, onupdate=utcnow)

class User(Base, Times):
    __tablename__="users"; id: Mapped[str]=mapped_column(String(36),primary_key=True,default=uid)
    email: Mapped[str]=mapped_column(String(320),unique=True,index=True); name: Mapped[str]=mapped_column(String(120)); password_hash: Mapped[str]=mapped_column(String(255)); is_active: Mapped[bool]=mapped_column(Boolean,default=True)
class Merchant(Base, Times):
    __tablename__="merchants"; id: Mapped[str]=mapped_column(String(36),primary_key=True,default=uid)
    name: Mapped[str]=mapped_column(String(160)); slug: Mapped[str]=mapped_column(String(120),unique=True,index=True)
class MerchantUser(Base, Times):
    __tablename__="merchant_users"; __table_args__=(UniqueConstraint("merchant_id","user_id"),)
    id: Mapped[str]=mapped_column(String(36),primary_key=True,default=uid); merchant_id: Mapped[str]=mapped_column(ForeignKey("merchants.id",ondelete="CASCADE"),index=True); user_id: Mapped[str]=mapped_column(ForeignKey("users.id",ondelete="CASCADE"),index=True); role: Mapped[str]=mapped_column(String(24),default="owner")
class AuthSession(Base):
    __tablename__="auth_sessions"; id: Mapped[str]=mapped_column(String(36),primary_key=True,default=uid)
    user_id: Mapped[str]=mapped_column(ForeignKey("users.id",ondelete="CASCADE"),index=True); token_hash: Mapped[str]=mapped_column(String(64),unique=True,index=True); csrf_hash: Mapped[str]=mapped_column(String(64)); expires_at: Mapped[datetime]=mapped_column(DateTime,index=True); revoked_at: Mapped[datetime|None]=mapped_column(DateTime,nullable=True); created_at: Mapped[datetime]=mapped_column(DateTime,default=utcnow)
class RazorpayConnection(Base, Times):
    __tablename__="razorpay_connections"; id: Mapped[str]=mapped_column(String(36),primary_key=True,default=uid); merchant_id: Mapped[str]=mapped_column(ForeignKey("merchants.id",ondelete="CASCADE"),unique=True,index=True); key_id_masked: Mapped[str|None]=mapped_column(String(40)); key_id_encrypted: Mapped[str|None]=mapped_column(Text); key_secret_encrypted: Mapped[str|None]=mapped_column(Text); webhook_secret_encrypted: Mapped[str|None]=mapped_column(Text); webhook_token: Mapped[str|None]=mapped_column(String(64),unique=True,index=True); mode: Mapped[str]=mapped_column(String(16),default="not_connected"); connection_status: Mapped[str]=mapped_column(String(24),default="not_connected"); webhook_status: Mapped[str]=mapped_column(String(24),default="not_verified"); last_verified_at: Mapped[datetime|None]=mapped_column(DateTime); last_sync_at: Mapped[datetime|None]=mapped_column(DateTime); sync_status: Mapped[str]=mapped_column(String(24),default="never"); sync_error: Mapped[str|None]=mapped_column(Text); imported_orders: Mapped[int]=mapped_column(Integer,default=0); imported_payments: Mapped[int]=mapped_column(Integer,default=0)

class DataIngestionRun(Base):
    __tablename__="data_ingestion_runs"; __table_args__=(UniqueConstraint("merchant_id","source","idempotency_key"),)
    id: Mapped[str]=mapped_column(String(36),primary_key=True,default=uid); merchant_id: Mapped[str]=mapped_column(ForeignKey("merchants.id",ondelete="CASCADE"),index=True); source: Mapped[str]=mapped_column(String(32),index=True); idempotency_key: Mapped[str]=mapped_column(String(128)); status: Mapped[str]=mapped_column(String(24),index=True); counts: Mapped[dict[str,Any]]=mapped_column(JSON,default=dict); error: Mapped[str|None]=mapped_column(Text); filename: Mapped[str|None]=mapped_column(String(180)); records: Mapped[list[dict[str,Any]]]=mapped_column(JSON,default=list); removed_at: Mapped[datetime|None]=mapped_column(DateTime,index=True); started_at: Mapped[datetime]=mapped_column(DateTime,default=utcnow,index=True); completed_at: Mapped[datetime|None]=mapped_column(DateTime)

class Customer(Base, Times):
    __tablename__="customers"; __table_args__=(UniqueConstraint("merchant_id","external_ref"),)
    id: Mapped[str]=mapped_column(String(36),primary_key=True,default=uid); merchant_id: Mapped[str]=mapped_column(ForeignKey("merchants.id",ondelete="CASCADE"),index=True); external_ref: Mapped[str]=mapped_column(String(120)); name: Mapped[str]=mapped_column(String(160)); email: Mapped[str]=mapped_column(String(320),index=True); phone: Mapped[str|None]=mapped_column(String(32)); historical_success_rate: Mapped[float]=mapped_column(Float,default=.7); preferred_method: Mapped[str]=mapped_column(String(32),default="card"); previous_failures: Mapped[int]=mapped_column(Integer,default=0)
class Order(Base, Times):
    __tablename__="orders"; __table_args__=(UniqueConstraint("merchant_id","external_ref"),)
    id: Mapped[str]=mapped_column(String(36),primary_key=True,default=uid); merchant_id: Mapped[str]=mapped_column(ForeignKey("merchants.id",ondelete="CASCADE"),index=True); customer_id: Mapped[str]=mapped_column(ForeignKey("customers.id"),index=True); external_ref: Mapped[str]=mapped_column(String(120)); amount_paise: Mapped[int]=mapped_column(Integer,index=True); currency: Mapped[str]=mapped_column(String(3),default="INR"); status: Mapped[str]=mapped_column(String(32),index=True); data_source: Mapped[str]=mapped_column(String(24),default="merchant_import",index=True)
class Payment(Base, Times):
    __tablename__="payments"; __table_args__=(UniqueConstraint("merchant_id","external_ref"),)
    id: Mapped[str]=mapped_column(String(36),primary_key=True,default=uid); merchant_id: Mapped[str]=mapped_column(ForeignKey("merchants.id",ondelete="CASCADE"),index=True); order_id: Mapped[str]=mapped_column(ForeignKey("orders.id"),index=True); external_ref: Mapped[str]=mapped_column(String(120)); amount_paise: Mapped[int]=mapped_column(Integer); currency: Mapped[str]=mapped_column(String(3),default="INR"); method: Mapped[str|None]=mapped_column(String(32),index=True); failure_code: Mapped[str|None]=mapped_column(String(80),index=True); failure_description: Mapped[str|None]=mapped_column(Text); bank: Mapped[str|None]=mapped_column(String(80)); status: Mapped[str]=mapped_column(String(32),index=True); data_source: Mapped[str]=mapped_column(String(24),default="merchant_import",index=True)
class PaymentAttempt(Base, Times):
    __tablename__="payment_attempts"; __table_args__=(UniqueConstraint("merchant_id","payment_id","attempt_number"),)
    id: Mapped[str]=mapped_column(String(36),primary_key=True,default=uid); merchant_id: Mapped[str]=mapped_column(ForeignKey("merchants.id",ondelete="CASCADE"),index=True); payment_id: Mapped[str]=mapped_column(ForeignKey("payments.id",ondelete="CASCADE"),index=True); attempt_number: Mapped[int]=mapped_column(Integer); method: Mapped[str]=mapped_column(String(32)); status: Mapped[str]=mapped_column(String(32),index=True); failure_code: Mapped[str|None]=mapped_column(String(80)); device: Mapped[str]=mapped_column(String(40)); checkout_duration_seconds: Mapped[int]=mapped_column(Integer,default=0)
class CheckoutEvent(Base, Times):
    __tablename__="checkout_events"; id: Mapped[str]=mapped_column(String(36),primary_key=True,default=uid); merchant_id: Mapped[str]=mapped_column(ForeignKey("merchants.id",ondelete="CASCADE"),index=True); customer_id: Mapped[str]=mapped_column(ForeignKey("customers.id"),index=True); order_id: Mapped[str|None]=mapped_column(ForeignKey("orders.id"),index=True); event_type: Mapped[str]=mapped_column(String(48),index=True); metadata_json: Mapped[dict[str,Any]]=mapped_column(JSON,default=dict)
class Subscription(Base, Times):
    __tablename__="subscriptions"; id: Mapped[str]=mapped_column(String(36),primary_key=True,default=uid); merchant_id: Mapped[str]=mapped_column(ForeignKey("merchants.id",ondelete="CASCADE"),index=True); customer_id: Mapped[str]=mapped_column(ForeignKey("customers.id"),index=True); external_ref: Mapped[str]=mapped_column(String(120),index=True); status: Mapped[str]=mapped_column(String(32),index=True); amount_paise: Mapped[int]=mapped_column(Integer)

class RiskEvent(Base, Times):
    __tablename__="risk_events"; __table_args__=(UniqueConstraint("merchant_id","payment_id","detector_version"),)
    id: Mapped[str]=mapped_column(String(36),primary_key=True,default=uid); merchant_id: Mapped[str]=mapped_column(ForeignKey("merchants.id",ondelete="CASCADE"),index=True); payment_id: Mapped[str]=mapped_column(ForeignKey("payments.id"),index=True); detector_version: Mapped[str]=mapped_column(String(32),default="risk-v1"); risk_score: Mapped[float]=mapped_column(Float); recovery_probability: Mapped[float]=mapped_column(Float); affected_revenue_paise: Mapped[int]=mapped_column(Integer); confidence: Mapped[float]=mapped_column(Float); root_cause: Mapped[str]=mapped_column(String(80),index=True); reason_codes: Mapped[list[str]]=mapped_column(JSON); evidence: Mapped[list[dict[str,Any]]]=mapped_column(JSON); status: Mapped[str]=mapped_column(String(32),default="open",index=True)
class AgentDecision(Base, Times):
    __tablename__="agent_decisions"; __table_args__=(UniqueConstraint("merchant_id","risk_event_id","decision_version"),)
    id: Mapped[str]=mapped_column(String(36),primary_key=True,default=uid); merchant_id: Mapped[str]=mapped_column(ForeignKey("merchants.id",ondelete="CASCADE"),index=True); risk_event_id: Mapped[str]=mapped_column(ForeignKey("risk_events.id"),index=True); decision_version: Mapped[str]=mapped_column(String(32),default="decision-v1"); selected_action: Mapped[str]=mapped_column(String(48),index=True); candidates: Mapped[list[dict[str,Any]]]=mapped_column(JSON); expected_recovery_paise: Mapped[int]=mapped_column(Integer); predicted_probability: Mapped[float]=mapped_column(Float); confidence: Mapped[float]=mapped_column(Float); policy_result: Mapped[dict[str,Any]]=mapped_column(JSON); policy_status: Mapped[str]=mapped_column(String(32),index=True); explanation: Mapped[str]=mapped_column(Text); model_version: Mapped[str]=mapped_column(String(64),default="deterministic-fallback-v1")
class Experiment(Base, Times):
    __tablename__="experiments"; id: Mapped[str]=mapped_column(String(36),primary_key=True,default=uid); merchant_id: Mapped[str]=mapped_column(ForeignKey("merchants.id",ondelete="CASCADE"),index=True); name: Mapped[str]=mapped_column(String(160)); segment: Mapped[str]=mapped_column(Text); status: Mapped[str]=mapped_column(String(24),default="running",index=True)
class ExperimentVariant(Base, Times):
    __tablename__="experiment_variants"; __table_args__=(UniqueConstraint("experiment_id","name"),)
    id: Mapped[str]=mapped_column(String(36),primary_key=True,default=uid); merchant_id: Mapped[str]=mapped_column(ForeignKey("merchants.id",ondelete="CASCADE"),index=True); experiment_id: Mapped[str]=mapped_column(ForeignKey("experiments.id",ondelete="CASCADE"),index=True); name: Mapped[str]=mapped_column(String(120)); action_type: Mapped[str]=mapped_column(String(48)); allocation_percent: Mapped[int]=mapped_column(Integer,default=33)
class RecoveryAction(Base, Times):
    __tablename__="recovery_actions"; id: Mapped[str]=mapped_column(String(36),primary_key=True,default=uid); merchant_id: Mapped[str]=mapped_column(ForeignKey("merchants.id",ondelete="CASCADE"),index=True); decision_id: Mapped[str]=mapped_column(ForeignKey("agent_decisions.id"),unique=True,index=True); payment_id: Mapped[str]=mapped_column(ForeignKey("payments.id"),index=True); experiment_variant_id: Mapped[str|None]=mapped_column(ForeignKey("experiment_variants.id"),index=True); action_type: Mapped[str]=mapped_column(String(48),index=True); status: Mapped[str]=mapped_column(String(32),index=True); idempotency_key: Mapped[str]=mapped_column(String(160),unique=True,index=True); execution_mode: Mapped[str]=mapped_column(String(32),default="pending"); provider_reference: Mapped[str|None]=mapped_column(String(160),index=True); provider_url: Mapped[str|None]=mapped_column(Text); execution_result: Mapped[dict[str,Any]]=mapped_column(JSON,default=dict); verification_status: Mapped[str]=mapped_column(String(32),default="not_started",index=True); verification_source: Mapped[str|None]=mapped_column(String(48)); razorpay_payment_id: Mapped[str|None]=mapped_column(String(120),index=True); actual_recovered_paise: Mapped[int]=mapped_column(Integer,default=0); executed_at: Mapped[datetime|None]=mapped_column(DateTime); verified_at: Mapped[datetime|None]=mapped_column(DateTime)
class Approval(Base, Times):
    __tablename__="approvals"; __table_args__=(UniqueConstraint("merchant_id","recovery_action_id"),)
    id: Mapped[str]=mapped_column(String(36),primary_key=True,default=uid); merchant_id: Mapped[str]=mapped_column(ForeignKey("merchants.id",ondelete="CASCADE"),index=True); recovery_action_id: Mapped[str]=mapped_column(ForeignKey("recovery_actions.id",ondelete="CASCADE"),index=True); reviewed_by_user_id: Mapped[str|None]=mapped_column(ForeignKey("users.id")); status: Mapped[str]=mapped_column(String(24),default="pending",index=True); reason: Mapped[str|None]=mapped_column(Text); reviewed_at: Mapped[datetime|None]=mapped_column(DateTime)
class ExperimentResult(Base, Times):
    __tablename__="experiment_results"; __table_args__=(UniqueConstraint("merchant_id","recovery_action_id"),)
    id: Mapped[str]=mapped_column(String(36),primary_key=True,default=uid); merchant_id: Mapped[str]=mapped_column(ForeignKey("merchants.id",ondelete="CASCADE"),index=True); experiment_id: Mapped[str]=mapped_column(ForeignKey("experiments.id",ondelete="CASCADE"),index=True); variant_id: Mapped[str]=mapped_column(ForeignKey("experiment_variants.id"),index=True); recovery_action_id: Mapped[str|None]=mapped_column(ForeignKey("recovery_actions.id")); predicted_probability: Mapped[float]=mapped_column(Float); predicted_recovery_paise: Mapped[int]=mapped_column(Integer); chosen_action: Mapped[str]=mapped_column(String(48)); actual_result: Mapped[str]=mapped_column(String(32)); actual_recovered_paise: Mapped[int]=mapped_column(Integer,default=0)
class StrategyPerformance(Base, Times):
    __tablename__="strategy_performance"; __table_args__=(UniqueConstraint("merchant_id","reason_code","action_type"),)
    id: Mapped[str]=mapped_column(String(36),primary_key=True,default=uid); merchant_id: Mapped[str]=mapped_column(ForeignKey("merchants.id",ondelete="CASCADE"),index=True); reason_code: Mapped[str]=mapped_column(String(80),index=True); action_type: Mapped[str]=mapped_column(String(48),index=True); participants: Mapped[int]=mapped_column(Integer,default=0); successes: Mapped[int]=mapped_column(Integer,default=0); recovered_paise: Mapped[int]=mapped_column(Integer,default=0)
class RecoveryAttribution(Base):
    __tablename__="recovery_attributions"; __table_args__=(UniqueConstraint("payment_id"),UniqueConstraint("razorpay_payment_id"))
    id: Mapped[str]=mapped_column(String(36),primary_key=True,default=uid); merchant_id: Mapped[str]=mapped_column(ForeignKey("merchants.id",ondelete="CASCADE"),index=True); recovery_action_id: Mapped[str]=mapped_column(ForeignKey("recovery_actions.id"),unique=True,index=True); payment_id: Mapped[str]=mapped_column(ForeignKey("payments.id"),index=True); razorpay_payment_id: Mapped[str|None]=mapped_column(String(120)); amount_recovered_paise: Mapped[int]=mapped_column(Integer); verification_status: Mapped[str]=mapped_column(String(32)); verified_at: Mapped[datetime]=mapped_column(DateTime,default=utcnow)

class RazorpayOrder(Base, Times):
    __tablename__="razorpay_orders"; __table_args__=(UniqueConstraint("merchant_id","razorpay_order_id"),)
    id: Mapped[str]=mapped_column(String(36),primary_key=True,default=uid); merchant_id: Mapped[str]=mapped_column(ForeignKey("merchants.id",ondelete="CASCADE"),index=True); internal_order_id: Mapped[str]=mapped_column(ForeignKey("orders.id"),index=True); razorpay_order_id: Mapped[str]=mapped_column(String(120),index=True); amount_paise: Mapped[int]=mapped_column(Integer); currency: Mapped[str]=mapped_column(String(3),default="INR"); status: Mapped[str]=mapped_column(String(32),index=True); raw_data: Mapped[dict[str,Any]]=mapped_column(JSON)
class RazorpayPayment(Base, Times):
    __tablename__="razorpay_payments"; __table_args__=(UniqueConstraint("merchant_id","razorpay_payment_id"),)
    id: Mapped[str]=mapped_column(String(36),primary_key=True,default=uid); merchant_id: Mapped[str]=mapped_column(ForeignKey("merchants.id",ondelete="CASCADE"),index=True); internal_payment_id: Mapped[str|None]=mapped_column(ForeignKey("payments.id"),index=True); razorpay_payment_id: Mapped[str]=mapped_column(String(120),index=True); razorpay_order_id: Mapped[str|None]=mapped_column(String(120),index=True); amount_paise: Mapped[int]=mapped_column(Integer); currency: Mapped[str]=mapped_column(String(3),default="INR"); status: Mapped[str]=mapped_column(String(32),index=True); method: Mapped[str|None]=mapped_column(String(32)); failure_code: Mapped[str|None]=mapped_column(String(80)); raw_data: Mapped[dict[str,Any]]=mapped_column(JSON)
class RazorpayPaymentLink(Base, Times):
    __tablename__="razorpay_payment_links"; __table_args__=(UniqueConstraint("merchant_id","razorpay_payment_link_id"),UniqueConstraint("recovery_action_id"))
    id: Mapped[str]=mapped_column(String(36),primary_key=True,default=uid); merchant_id: Mapped[str]=mapped_column(ForeignKey("merchants.id",ondelete="CASCADE"),index=True); recovery_action_id: Mapped[str]=mapped_column(ForeignKey("recovery_actions.id"),index=True); razorpay_payment_link_id: Mapped[str|None]=mapped_column(String(120),index=True); short_url: Mapped[str|None]=mapped_column(Text); amount_paise: Mapped[int]=mapped_column(Integer); status: Mapped[str]=mapped_column(String(32),index=True); mode: Mapped[str]=mapped_column(String(32)); raw_data: Mapped[dict[str,Any]]=mapped_column(JSON)
class WebhookEvent(Base):
    __tablename__="webhook_events"; id: Mapped[str]=mapped_column(String(36),primary_key=True,default=uid); event_id: Mapped[str]=mapped_column(String(160),unique=True,index=True); event_type: Mapped[str]=mapped_column(String(80),index=True); payload_sha256: Mapped[str]=mapped_column(String(64)); signature_valid: Mapped[bool]=mapped_column(Boolean); status: Mapped[str]=mapped_column(String(32),index=True); merchant_id: Mapped[str|None]=mapped_column(ForeignKey("merchants.id"),index=True); payload: Mapped[dict[str,Any]]=mapped_column(JSON); error: Mapped[str|None]=mapped_column(Text); received_at: Mapped[datetime]=mapped_column(DateTime,default=utcnow,index=True); processed_at: Mapped[datetime|None]=mapped_column(DateTime)
class AuditLog(Base):
    __tablename__="audit_logs"; id: Mapped[str]=mapped_column(String(36),primary_key=True,default=uid); merchant_id: Mapped[str]=mapped_column(ForeignKey("merchants.id",ondelete="CASCADE"),index=True); actor_type: Mapped[str]=mapped_column(String(32),default="agent"); actor_id: Mapped[str|None]=mapped_column(String(120)); action_id: Mapped[str|None]=mapped_column(ForeignKey("recovery_actions.id"),index=True); decision_id: Mapped[str|None]=mapped_column(ForeignKey("agent_decisions.id"),index=True); event_type: Mapped[str]=mapped_column(String(80),index=True); detail: Mapped[dict[str,Any]]=mapped_column(JSON); amount_paise: Mapped[int]=mapped_column(Integer,default=0); request_id: Mapped[str|None]=mapped_column(String(64),index=True); created_at: Mapped[datetime]=mapped_column(DateTime,default=utcnow,index=True)
class AgentEvent(Base):
    __tablename__="agent_events"; id: Mapped[str]=mapped_column(String(36),primary_key=True,default=uid); merchant_id: Mapped[str]=mapped_column(ForeignKey("merchants.id",ondelete="CASCADE"),index=True); action_id: Mapped[str|None]=mapped_column(ForeignKey("recovery_actions.id"),index=True); stage: Mapped[str]=mapped_column(String(32),index=True); title: Mapped[str]=mapped_column(String(160)); detail: Mapped[str]=mapped_column(Text); status: Mapped[str]=mapped_column(String(32),default="complete"); amount_paise: Mapped[int]=mapped_column(Integer,default=0); created_at: Mapped[datetime]=mapped_column(DateTime,default=utcnow,index=True)
class MerchantPolicy(Base, Times):
    __tablename__="merchant_policies"; id: Mapped[str]=mapped_column(String(36),primary_key=True,default=uid); merchant_id: Mapped[str]=mapped_column(ForeignKey("merchants.id",ondelete="CASCADE"),unique=True,index=True); automatic_threshold_paise: Mapped[int]=mapped_column(Integer,default=500000); approval_threshold_paise: Mapped[int]=mapped_column(Integer,default=1500000); blocked_threshold_paise: Mapped[int]=mapped_column(Integer,default=5000000); max_retries: Mapped[int]=mapped_column(Integer,default=2); minimum_confidence: Mapped[float]=mapped_column(Float,default=.65); cooldown_minutes: Mapped[int]=mapped_column(Integer,default=60); allowed_actions: Mapped[list[str]]=mapped_column(JSON)

Index("ix_payment_tenant_status",Payment.merchant_id,Payment.status,Payment.created_at)
Index("ix_risk_tenant_status_amount",RiskEvent.merchant_id,RiskEvent.status,RiskEvent.affected_revenue_paise)
Index("ix_action_tenant_status",RecoveryAction.merchant_id,RecoveryAction.status,RecoveryAction.created_at)
def create_all() -> None: Base.metadata.create_all(bind=engine)
def ensure_compat_schema() -> None:
    """Adds compatible columns for local create_all databases made before migrations."""
    columns={x["name"] for x in inspect(engine).get_columns("razorpay_connections")}
    definitions={"key_id_encrypted":"TEXT","key_secret_encrypted":"TEXT","webhook_secret_encrypted":"TEXT","webhook_token":"VARCHAR(64)","last_sync_at":"DATETIME","sync_status":"VARCHAR(24)","sync_error":"TEXT","imported_orders":"INTEGER","imported_payments":"INTEGER"}
    with engine.begin() as connection:
        for name,definition in definitions.items():
            if name not in columns:connection.execute(text(f"ALTER TABLE razorpay_connections ADD COLUMN {name} {definition}"))
        connection.execute(text("CREATE UNIQUE INDEX IF NOT EXISTS ix_razorpay_connections_webhook_token ON razorpay_connections (webhook_token)"))
        if "data_ingestion_runs" in inspect(engine).get_table_names():
            ingestion_columns={x["name"] for x in inspect(engine).get_columns("data_ingestion_runs")}
            for name,definition in {"filename":"VARCHAR(180)","records":"JSON","removed_at":"DATETIME"}.items():
                if name not in ingestion_columns:connection.execute(text(f"ALTER TABLE data_ingestion_runs ADD COLUMN {name} {definition}"))
            connection.execute(text("CREATE INDEX IF NOT EXISTS ix_data_ingestion_runs_removed_at ON data_ingestion_runs (removed_at)"))
